#!/bin/bash

# Check El Capitan's Mono install location
# And Mono 5's install location
# And the configured location in /etc/paths.d
MONO_FRAMEWORK_PATH=/Library/Frameworks/Mono.framework/Versions/Current
PATH="${PATH}:/usr/local/bin:${MONO_FRAMEWORK_PATH}/Commands"
if [ -r /etc/paths.d/mono-commands ]
then
    PATH="${PATH}:$(cat /etc/paths.d/mono-commands)"
fi
export PATH

# Look for mono now that we've assembled our PATH
MONO=$(which mono)

if [ -z "$MONO" -o ! -x "$MONO" ]
then
    # We could not find mono. The wiki explains how to install.
    open 'https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX'
else
    # Mono found, so we can run CKAN
    # The exe is called ckan.exe
    ASSEMBLY=ckan.exe
    # The script and ckan.exe are in the same folder, go there now
    MACOS_PATH="$(cd "$(dirname "$0")" && pwd)"
    cd "$MACOS_PATH"
    # Set up and run mono
    export MONO_MWF_USE_CARBON_BACKEND=1
    export GDIPLUS_NOX=1
    export DYLD_FALLBACK_LIBRARY_PATH="$MACOS_PATH:$MONO_FRAMEWORK_PATH/lib:/lib:/usr/lib"
    "$MONO" --arch=32 "$ASSEMBLY" "$@"
fi
