#!/bin/bash

# dotnet uses a different SpecialFolder.LocalApplicationData path than Mono did
MONO_DIR="${HOME}/.local/share/CKAN"
DOTNET_DIR="${HOME}/Library/Application Support/CKAN"
if [[ -d "${MONO_DIR}" && ! -e "${DOTNET_DIR}" ]]
then
    mv "${MONO_DIR}" "${DOTNET_DIR}"
    ln -s "${DOTNET_DIR}" "${MONO_DIR}"
fi

# The script is in the same folder as the arch-specific folders, go there now.
# Mac always runs bash scripts in an x86_64 environment if Rosetta 2 is installed,
# which makes uname useless for determining architecture.
if [[ $(sysctl -ni hw.optional.arm64) == 1 ]]
then
    ARCH=arm64
else
    ARCH=x86_64
fi
MACOS_PATH="$(cd "$(dirname "$0")/${ARCH}" && pwd)"
cd "$MACOS_PATH"

osascript <<END
tell application "Terminal"
    do script "cd \"`pwd`\"; ./CKAN-CmdLine consoleui"
end tell
END
