FROM mono:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip git jsonlint && \
    apt-get clean
RUN pip3 install 'git+https://github.com/KSP-CKAN/NetKAN-Infra#subdirectory=netkan'

ADD netkan.exe /usr/local/bin/.
ADD ckan.exe /usr/local/bin/.

RUN mkdir -p /ckans /repo
