//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. (I WISH!)
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKAN.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() { }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new SingleAssemblyResourceManager("CKAN.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_forward {
            get {
                object obj = ResourceManager.GetObject("arrow_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_upward {
            get {
                object obj = ResourceManager.GetObject("arrow_upward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backward {
            get {
                object obj = ResourceManager.GetObject("backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CKAN metadata (*.ckan)|*.ckan.
        /// </summary>
        internal static string CKANFileFilter {
            get {
                return ResourceManager.GetString("CKANFileFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export Mod List.
        /// </summary>
        internal static string ExportInstalledModsDialogTitle {
            get {
                return ResourceManager.GetString("ExportInstalledModsDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward {
            get {
                object obj = ResourceManager.GetObject("forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ksp {
            get {
                object obj = ResourceManager.GetObject("ksp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile {
            get {
                object obj = ResourceManager.GetObject("smile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textClear {
            get {
                object obj = ResourceManager.GetObject("textClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumbup {
            get {
                object obj = ResourceManager.GetObject("thumbup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static string AboutDialogLabel2Text {
            get { return (string)(ResourceManager.GetObject("AboutDialogLabel2Text", resourceCulture)); }
        }

        internal static string CloneFakeKspDialogOpenFilter {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogOpenFilter", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogEnterName {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogEnterName", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogEnterPath {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogEnterPath", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogCloningInstance {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogCloningInstance", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogInstanceNotValid {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogInstanceNotValid", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogDlcVersionMalformatted {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogDlcVersionMalformatted", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogDestinationNotEmpty {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogDestinationNotEmpty", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogCloneFailed {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogCloneFailed", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogSuccessfulClone {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogSuccessfulClone", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogCreatingInstance {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogCreatingInstance", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogNameAlreadyUsed {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogNameAlreadyUsed", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogFakeFailed {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogFakeFailed", resourceCulture)); }
        }
        internal static string CloneFakeKspDialogSuccessfulCreate {
            get { return (string)(ResourceManager.GetObject("CloneFakeKspDialogSuccessfulCreate", resourceCulture)); }
        }

        internal static string CompatibleKspVersionsDialogNone {
            get { return (string)(ResourceManager.GetObject("CompatibleKspVersionsDialogNone", resourceCulture)); }
        }
        internal static string CompatibleKspVersionsDialogKSPUpdated {
            get { return (string)(ResourceManager.GetObject("CompatibleKspVersionsDialogKSPUpdated", resourceCulture)); }
        }
        internal static string CompatibleKspVersionsDialogVersionDetails {
            get { return (string)(ResourceManager.GetObject("CompatibleKspVersionsDialogVersionDetails", resourceCulture)); }
        }
        internal static string CompatibleKspVersionsDialogInvalidFormat {
            get { return (string)(ResourceManager.GetObject("CompatibleKspVersionsDialogInvalidFormat", resourceCulture)); }
        }
        internal static string CompatibleKspVersionsDialogErrorTitle {
            get { return (string)(ResourceManager.GetObject("CompatibleKspVersionsDialogErrorTitle", resourceCulture)); }
        }

        internal static string ConfigurationParseError {
            get { return (string)(ResourceManager.GetObject("ConfigurationParseError", resourceCulture)); }
        }

        internal static string GUIModNSlashA {
            get { return (string)(ResourceManager.GetObject("GUIModNSlashA", resourceCulture)); }
        }
        internal static string GUIModUnknown {
            get { return (string)(ResourceManager.GetObject("GUIModUnknown", resourceCulture)); }
        }
        internal static string GUIModMethodNotCKAN {
            get { return (string)(ResourceManager.GetObject("GUIModMethodNotCKAN", resourceCulture)); }
        }
        internal static string GUIModKSPCompatibilityLong {
            get { return (string)(ResourceManager.GetObject("GUIModKSPCompatibilityLong", resourceCulture)); }
        }

        internal static string MainAutoUpdateFailed {
            get { return (string)(ResourceManager.GetObject("MainAutoUpdateFailed", resourceCulture)); }
        }
        internal static string MainQuitWithConflicts {
            get { return (string)(ResourceManager.GetObject("MainQuitWithConflicts", resourceCulture)); }
        }
        internal static string MainQuit {
            get { return (string)(ResourceManager.GetObject("MainQuit", resourceCulture)); }
        }
        internal static string MainGoBack {
            get { return (string)(ResourceManager.GetObject("MainGoBack", resourceCulture)); }
        }
        internal static string MainQuitWithUnmetDeps {
            get { return (string)(ResourceManager.GetObject("MainQuitWithUnmetDeps", resourceCulture)); }
        }
        internal static string MainQuitWIthUnappliedChanges {
            get { return (string)(ResourceManager.GetObject("MainQuitWIthUnappliedChanges", resourceCulture)); }
        }
        internal static string MainUpgradingWaitTitle {
            get { return (string)(ResourceManager.GetObject("MainUpgradingWaitTitle", resourceCulture)); }
        }
        internal static string MainUpgradingTo {
            get { return (string)(ResourceManager.GetObject("MainUpgradingTo", resourceCulture)); }
        }
        internal static string MainDepNotSatisfied {
            get { return (string)(ResourceManager.GetObject("MainDepNotSatisfied", resourceCulture)); }
        }
        internal static string MainFilterAll {
            get { return (string)(ResourceManager.GetObject("MainFilterAll", resourceCulture)); }
        }
        internal static string MainFilterIncompatible {
            get { return (string)(ResourceManager.GetObject("MainFilterIncompatible", resourceCulture)); }
        }
        internal static string MainFilterInstalled {
            get { return (string)(ResourceManager.GetObject("MainFilterInstalled", resourceCulture)); }
        }
        internal static string MainFilterUpgradeable {
            get { return (string)(ResourceManager.GetObject("MainFilterUpgradeable", resourceCulture)); }
        }
        internal static string MainFilterReplaceable {
            get { return (string)(ResourceManager.GetObject("MainFilterReplaceable", resourceCulture)); }
        }
        internal static string MainFilterCached {
            get { return (string)(ResourceManager.GetObject("MainFilterCached", resourceCulture)); }
        }
        internal static string MainFilterUncached {
            get { return (string)(ResourceManager.GetObject("MainFilterUncached", resourceCulture)); }
        }
        internal static string MainFilterNew {
            get { return (string)(ResourceManager.GetObject("MainFilterNew", resourceCulture)); }
        }
        internal static string MainFilterNotInstalled {
            get { return (string)(ResourceManager.GetObject("MainFilterNotInstalled", resourceCulture)); }
        }
        internal static string MainFilterCompatible {
            get { return (string)(ResourceManager.GetObject("MainFilterCompatible", resourceCulture)); }
        }
        internal static string MainFilterLabel {
            get { return (string)(ResourceManager.GetObject("MainFilterLabel", resourceCulture)); }
        }
        internal static string MainFilterTag {
            get { return (string)(ResourceManager.GetObject("MainFilterTag", resourceCulture)); }
        }
        internal static string MainFilterUntagged {
            get { return (string)(ResourceManager.GetObject("MainFilterUntagged", resourceCulture)); }
        }
        internal static string MainLaunchWithIncompatible {
            get { return (string)(ResourceManager.GetObject("MainLaunchWithIncompatible", resourceCulture)); }
        }
        internal static string MainLaunch {
            get { return (string)(ResourceManager.GetObject("MainLaunch", resourceCulture)); }
        }
        internal static string MainLaunchFailed {
            get { return (string)(ResourceManager.GetObject("MainLaunchFailed", resourceCulture)); }
        }
        internal static string MainModPack {
            get { return (string)(ResourceManager.GetObject("MainModPack", resourceCulture)); }
        }
        internal static string MainPlainText {
            get { return (string)(ResourceManager.GetObject("MainPlainText", resourceCulture)); }
        }
        internal static string MainMarkdown {
            get { return (string)(ResourceManager.GetObject("MainMarkdown", resourceCulture)); }
        }
        internal static string MainBBCode {
            get { return (string)(ResourceManager.GetObject("MainBBCode", resourceCulture)); }
        }
        internal static string MainCSV {
            get { return (string)(ResourceManager.GetObject("MainCSV", resourceCulture)); }
        }
        internal static string MainTSV {
            get { return (string)(ResourceManager.GetObject("MainTSV", resourceCulture)); }
        }
        internal static string MainNotFound {
            get { return (string)(ResourceManager.GetObject("MainNotFound", resourceCulture)); }
        }
        internal static string MainReinstallConfirm {
            get { return (string)(ResourceManager.GetObject("MainReinstallConfirm", resourceCulture)); }
        }

        internal static string AllModVersionsInstallPrompt {
            get { return (string)(ResourceManager.GetObject("AllModVersionsInstallPrompt", resourceCulture)); }
        }
        internal static string AllModVersionsInstallYes {
            get { return (string)(ResourceManager.GetObject("AllModVersionsInstallYes", resourceCulture)); }
        }
        internal static string AllModVersionsInstallNo {
            get { return (string)(ResourceManager.GetObject("AllModVersionsInstallNo", resourceCulture)); }
        }

        internal static string MainChangesetMetapackage {
            get { return (string)(ResourceManager.GetObject("MainChangesetMetapackage", resourceCulture)); }
        }
        internal static string MainChangesetCached {
            get { return (string)(ResourceManager.GetObject("MainChangesetCached", resourceCulture)); }
        }
        internal static string MainChangesetHostSize {
            get { return (string)(ResourceManager.GetObject("MainChangesetHostSize", resourceCulture)); }
        }
        internal static string MainChangesetUpdateSelected {
            get { return (string)(ResourceManager.GetObject("MainChangesetUpdateSelected", resourceCulture)); }
        }
        internal static string MainChangesetNewInstall {
            get { return (string)(ResourceManager.GetObject("MainChangesetNewInstall", resourceCulture)); }
        }

        internal static string MainImportTitle {
            get { return (string)(ResourceManager.GetObject("MainImportTitle", resourceCulture)); }
        }
        internal static string MainImportFilter {
            get { return (string)(ResourceManager.GetObject("MainImportFilter", resourceCulture)); }
        }
        internal static string MainImportWaitTitle {
            get { return (string)(ResourceManager.GetObject("MainImportWaitTitle", resourceCulture)); }
        }

        internal static string MainInstallWaitTitle {
            get { return (string)(ResourceManager.GetObject("MainInstallWaitTitle", resourceCulture)); }
        }
        internal static string MainInstallDepNotSatisfied {
            get { return (string)(ResourceManager.GetObject("MainInstallDepNotSatisfied", resourceCulture)); }
        }
        internal static string MainInstallNotFound {
            get { return (string)(ResourceManager.GetObject("MainInstallNotFound", resourceCulture)); }
        }
        internal static string MainInstallBadMetadata {
            get { return (string)(ResourceManager.GetObject("MainInstallBadMetadata", resourceCulture)); }
        }
        internal static string MainInstallFileExists {
            get { return (string)(ResourceManager.GetObject("MainInstallFileExists", resourceCulture)); }
        }
        internal static string MainInstallUnownedFileExists {
            get { return (string)(ResourceManager.GetObject("MainInstallUnownedFileExists", resourceCulture)); }
        }
        internal static string MainInstallGameDataReverted {
            get { return (string)(ResourceManager.GetObject("MainInstallGameDataReverted", resourceCulture)); }
        }
        internal static string MainInstallOpenSettingsPrompt {
            get { return (string)(ResourceManager.GetObject("MainInstallOpenSettingsPrompt", resourceCulture)); }
        }
        internal static string MainInstallOpenSettings {
            get { return (string)(ResourceManager.GetObject("MainInstallOpenSettings", resourceCulture)); }
        }
        internal static string MainInstallNo {
            get { return (string)(ResourceManager.GetObject("MainInstallNo", resourceCulture)); }
        }
        internal static string MainInstallLibCurlMissing {
            get { return (string)(ResourceManager.GetObject("MainInstallLibCurlMissing", resourceCulture)); }
        }
        internal static string MainInstallModSuccess {
            get { return (string)(ResourceManager.GetObject("MainInstallModSuccess", resourceCulture)); }
        }
        internal static string MainInstallSuccess {
            get { return (string)(ResourceManager.GetObject("MainInstallSuccess", resourceCulture)); }
        }
        internal static string MainInstallCancelTooLate {
            get { return (string)(ResourceManager.GetObject("MainInstallCancelTooLate", resourceCulture)); }
        }
        internal static string MainInstallCancelAfterInstall {
            get { return (string)(ResourceManager.GetObject("MainInstallCancelAfterInstall", resourceCulture)); }
        }
        internal static string MainInstallProcessComplete {
            get { return (string)(ResourceManager.GetObject("MainInstallProcessComplete", resourceCulture)); }
        }
        internal static string MainInstallProcessCanceled {
            get { return (string)(ResourceManager.GetObject("MainInstallProcessCanceled", resourceCulture)); }
        }
        internal static string MainInstallCanceledManually {
            get { return (string)(ResourceManager.GetObject("MainInstallCanceledManually", resourceCulture)); }
        }
        internal static string MainInstallInstallCanceled {
            get { return (string)(ResourceManager.GetObject("MainInstallInstallCanceled", resourceCulture)); }
        }
        internal static string MainInstallErrorInstalling {
            get { return (string)(ResourceManager.GetObject("MainInstallErrorInstalling", resourceCulture)); }
        }
        internal static string MainInstallUnknownError {
            get { return (string)(ResourceManager.GetObject("MainInstallUnknownError", resourceCulture)); }
        }
        internal static string MainInstallKnownError {
            get { return (string)(ResourceManager.GetObject("MainInstallKnownError", resourceCulture)); }
        }
        internal static string MainInstallFailed {
            get { return (string)(ResourceManager.GetObject("MainInstallFailed", resourceCulture)); }
        }
        internal static string MainInstallProvidedBy {
            get { return (string)(ResourceManager.GetObject("MainInstallProvidedBy", resourceCulture)); }
        }

        internal static string ModInfoNSlashA {
            get { return (string)(ResourceManager.GetObject("ModInfoNSlashA", resourceCulture)); }
        }
        internal static string ModInfoVirtual {
            get { return (string)(ResourceManager.GetObject("ModInfoVirtual", resourceCulture)); }
        }
        internal static string ModInfoNotIndexed {
            get { return (string)(ResourceManager.GetObject("ModInfoNotIndexed", resourceCulture)); }
        }
        internal static string ModInfoNotCached {
            get { return (string)(ResourceManager.GetObject("ModInfoNotCached", resourceCulture)); }
        }
        internal static string ModInfoCached {
            get { return (string)(ResourceManager.GetObject("ModInfoCached", resourceCulture)); }
        }

        internal static string MainModListWaitTitle {
            get { return (string)(ResourceManager.GetObject("MainModListWaitTitle", resourceCulture)); }
        }
        internal static string MainModListLoadingRegistry {
            get { return (string)(ResourceManager.GetObject("MainModListLoadingRegistry", resourceCulture)); }
        }
        internal static string MainModListLoadingInstalled {
            get { return (string)(ResourceManager.GetObject("MainModListLoadingInstalled", resourceCulture)); }
        }
        internal static string MainModListLoadingAvailable {
            get { return (string)(ResourceManager.GetObject("MainModListLoadingAvailable", resourceCulture)); }
        }
        internal static string MainModListLoadingIncompatible {
            get { return (string)(ResourceManager.GetObject("MainModListLoadingIncompatible", resourceCulture)); }
        }
        internal static string MainModListRestoringChangeset {
            get { return (string)(ResourceManager.GetObject("MainModListRestoringChangeset", resourceCulture)); }
        }
        internal static string MainModListPreservingNew {
            get { return (string)(ResourceManager.GetObject("MainModListPreservingNew", resourceCulture)); }
        }
        internal static string MainModListPopulatingList {
            get { return (string)(ResourceManager.GetObject("MainModListPopulatingList", resourceCulture)); }
        }
        internal static string MainModListUpdatingFilters {
            get { return (string)(ResourceManager.GetObject("MainModListUpdatingFilters", resourceCulture)); }
        }
        internal static string MainModListCompatible {
            get { return (string)(ResourceManager.GetObject("MainModListCompatible", resourceCulture)); }
        }
        internal static string MainModListInstalled {
            get { return (string)(ResourceManager.GetObject("MainModListInstalled", resourceCulture)); }
        }
        internal static string MainModListUpgradeable {
            get { return (string)(ResourceManager.GetObject("MainModListUpgradeable", resourceCulture)); }
        }
        internal static string MainModListReplaceable {
            get { return (string)(ResourceManager.GetObject("MainModListReplaceable", resourceCulture)); }
        }
        internal static string MainModListCached {
            get { return (string)(ResourceManager.GetObject("MainModListCached", resourceCulture)); }
        }
        internal static string MainModListUncached {
            get { return (string)(ResourceManager.GetObject("MainModListUncached", resourceCulture)); }
        }
        internal static string MainModListNewlyCompatible {
            get { return (string)(ResourceManager.GetObject("MainModListNewlyCompatible", resourceCulture)); }
        }
        internal static string MainModListNotInstalled {
            get { return (string)(ResourceManager.GetObject("MainModListNotInstalled", resourceCulture)); }
        }
        internal static string MainModListIncompatible {
            get { return (string)(ResourceManager.GetObject("MainModListIncompatible", resourceCulture)); }
        }
        internal static string MainModListAll {
            get { return (string)(ResourceManager.GetObject("MainModListAll", resourceCulture)); }
        }
        internal static string MainModListUpdatingTray {
            get { return (string)(ResourceManager.GetObject("MainModListUpdatingTray", resourceCulture)); }
        }
        internal static string MainModListAutoDetected {
            get { return (string)(ResourceManager.GetObject("MainModListAutoDetected", resourceCulture)); }
        }
        internal static string MainModListUnknownFilter {
            get { return (string)(ResourceManager.GetObject("MainModListUnknownFilter", resourceCulture)); }
        }

        internal static string MainRecommendationsTitle {
            get { return (string)(ResourceManager.GetObject("MainRecommendationsTitle", resourceCulture)); }
        }
        internal static string MainRecommendationsNoneFound {
            get { return (string)(ResourceManager.GetObject("MainRecommendationsNoneFound", resourceCulture)); }
        }

        internal static string MainRepoWaitTitle {
            get { return (string)(ResourceManager.GetObject("MainRepoWaitTitle", resourceCulture)); }
        }
        internal static string MainRepoContacting {
            get { return (string)(ResourceManager.GetObject("MainRepoContacting", resourceCulture)); }
        }
        internal static string MainRepoScanning {
            get { return (string)(ResourceManager.GetObject("MainRepoScanning", resourceCulture)); }
        }
        internal static string MainRepoUpdating {
            get { return (string)(ResourceManager.GetObject("MainRepoUpdating", resourceCulture)); }
        }
        internal static string MainRepoFailedToConnect {
            get { return (string)(ResourceManager.GetObject("MainRepoFailedToConnect", resourceCulture)); }
        }
        internal static string MainRepoUpToDate {
            get { return (string)(ResourceManager.GetObject("MainRepoUpToDate", resourceCulture)); }
        }
        internal static string MainRepoFailed {
            get { return (string)(ResourceManager.GetObject("MainRepoFailed", resourceCulture)); }
        }
        internal static string MainRepoSuccess {
            get { return (string)(ResourceManager.GetObject("MainRepoSuccess", resourceCulture)); }
        }
        internal static string MainRepoAutoRefreshPrompt {
            get { return (string)(ResourceManager.GetObject("MainRepoAutoRefreshPrompt", resourceCulture)); }
        }
        internal static string MainRepoBalloonTipDetails {
            get { return (string)(ResourceManager.GetObject("MainRepoBalloonTipDetails", resourceCulture)); }
        }
        internal static string MainRepoBalloonTipTooltip {
            get { return (string)(ResourceManager.GetObject("MainRepoBalloonTipTooltip", resourceCulture)); }
        }

        internal static string MainTrayIconResume {
            get { return (string)(ResourceManager.GetObject("MainTrayIconResume", resourceCulture)); }
        }
        internal static string MainTrayIconPause {
            get { return (string)(ResourceManager.GetObject("MainTrayIconPause", resourceCulture)); }
        }
        internal static string MainTrayNoUpdates {
            get { return (string)(ResourceManager.GetObject("MainTrayNoUpdates", resourceCulture)); }
        }
        internal static string MainTrayUpdatesAvailable {
            get { return (string)(ResourceManager.GetObject("MainTrayUpdatesAvailable", resourceCulture)); }
        }
        internal static string MainWaitPleaseWait {
            get { return (string)(ResourceManager.GetObject("MainWaitPleaseWait", resourceCulture)); }
        }
        internal static string MainWaitDone {
            get { return (string)(ResourceManager.GetObject("MainWaitDone", resourceCulture)); }
        }

        internal static string ManageKspInstancesNotValid {
            get { return (string)(ResourceManager.GetObject("ManageKspInstancesNotValid", resourceCulture)); }
        }

        internal static string ManageKspInstancesDirectoryDeleted {
            get { return (string)(ResourceManager.GetObject("ManageKspInstancesDirectoryDeleted", resourceCulture)); }
        }

        internal static string NewRepoDialogFailed {
            get { return (string)(ResourceManager.GetObject("NewRepoDialogFailed", resourceCulture)); }
        }

        internal static string PluginsDialogFilter {
            get { return (string)(ResourceManager.GetObject("PluginsDialogFilter", resourceCulture)); }
        }

        internal static string SettingsDialogSummmary {
            get { return (string)(ResourceManager.GetObject("SettingsDialogSummmary", resourceCulture)); }
        }
        internal static string SettingsDialogSummaryInvalid {
            get { return (string)(ResourceManager.GetObject("SettingsDialogSummaryInvalid", resourceCulture)); }
        }
        internal static string SettingsDialogCacheDescrip {
            get { return (string)(ResourceManager.GetObject("SettingsDialogCacheDescrip", resourceCulture)); }
        }
        internal static string SettingsDialogDeleteConfirm {
            get { return (string)(ResourceManager.GetObject("SettingsDialogDeleteConfirm", resourceCulture)); }
        }
        internal static string SettingsDialogUpdateFailed {
            get { return (string)(ResourceManager.GetObject("SettingsDialogUpdateFailed", resourceCulture)); }
        }

        internal static string AddAuthTokenTitle {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenTitle", resourceCulture)); }
        }
        internal static string AddAuthTokenHost {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenHost", resourceCulture)); }
        }
        internal static string AddAuthTokenToken {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenToken", resourceCulture)); }
        }
        internal static string AddAuthTokenAccept {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenAccept", resourceCulture)); }
        }
        internal static string AddAuthTokenCancel {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenCancel", resourceCulture)); }
        }
        internal static string AddAuthTokenHostRequired {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenHostRequired", resourceCulture)); }
        }
        internal static string AddAuthTokenTokenRequired {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenTokenRequired", resourceCulture)); }
        }
        internal static string AddAuthTokenInvalidHost {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenInvalidHost", resourceCulture)); }
        }
        internal static string AddAuthTokenDupHost {
            get { return (string)(ResourceManager.GetObject("AddAuthTokenDupHost", resourceCulture)); }
        }

        internal static string URLHandlersPrompt {
            get { return (string)(ResourceManager.GetObject("URLHandlersPrompt", resourceCulture)); }
        }

        internal static string UtilCopyLink {
            get { return (string)(ResourceManager.GetObject("UtilCopyLink", resourceCulture)); }
        }

        internal static string StatusInstanceLabelText {
            get { return (string)(ResourceManager.GetObject("StatusInstanceLabelText", resourceCulture)); }
        }
        internal static string ModuleLabelListFavourites {
            get { return (string)(ResourceManager.GetObject("ModuleLabelListFavourites", resourceCulture)); }
        }
        internal static string ModuleLabelListHidden {
            get { return (string)(ResourceManager.GetObject("ModuleLabelListHidden", resourceCulture)); }
        }
        internal static string ModuleLabelListGlobal {
            get { return (string)(ResourceManager.GetObject("ModuleLabelListGlobal", resourceCulture)); }
        }
        internal static string EditLabelsDialogConfirmDelete {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogConfirmDelete", resourceCulture)); }
        }
        internal static string EditLabelsDialogSavePrompt {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogSavePrompt", resourceCulture)); }
        }
        internal static string EditLabelsDialogNoRecord {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogNoRecord", resourceCulture)); }
        }
        internal static string EditLabelsDialogNameRequired {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogNameRequired", resourceCulture)); }
        }
        internal static string EditLabelsDialogAlreadyExists {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogAlreadyExists", resourceCulture)); }
        }
        internal static string EditLabelsDialogDelete {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogDelete", resourceCulture)); }
        }
        internal static string EditLabelsDialogCancel {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogCancel", resourceCulture)); }
        }
        internal static string EditLabelsDialogSave {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogSave", resourceCulture)); }
        }
        internal static string EditLabelsDialogDiscard {
            get { return (string)(ResourceManager.GetObject("EditLabelsDialogDiscard", resourceCulture)); }
        }
        internal static string MainChangesetWarningInstallingModuleWithLabel {
            get { return (string)(ResourceManager.GetObject("MainChangesetWarningInstallingModuleWithLabel", resourceCulture)); }
        }
        internal static string EditLabelsToolTipName {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipName", resourceCulture)); }
        }
        internal static string EditLabelsToolTipColor {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipColor", resourceCulture)); }
        }
        internal static string EditLabelsToolTipInstance {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipInstance", resourceCulture)); }
        }
        internal static string EditLabelsToolTipHide {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipHide", resourceCulture)); }
        }
        internal static string EditLabelsToolTipNotifyOnChanges {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipNotifyOnChanges", resourceCulture)); }
        }
        internal static string EditLabelsToolTipRemoveOnChanges {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipRemoveOnChanges", resourceCulture)); }
        }
        internal static string EditLabelsToolTipAlertOnInstall {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipAlertOnInstall", resourceCulture)); }
        }
        internal static string EditLabelsToolTipRemoveOnInstall {
            get { return (string)(ResourceManager.GetObject("EditLabelsToolTipRemoveOnInstall", resourceCulture)); }
        }
        internal static string MainLabelsUpdateMessage {
            get { return (string)(ResourceManager.GetObject("MainLabelsUpdateMessage", resourceCulture)); }
        }
        internal static string MainLabelsUpdateTitle {
            get { return (string)(ResourceManager.GetObject("MainLabelsUpdateTitle", resourceCulture)); }
        }
        internal static string MainLabelsUntagged {
            get { return (string)(ResourceManager.GetObject("MainLabelsUntagged", resourceCulture)); }
        }

        internal static string EditModpackBadIdentifier {
            get { return (string)(ResourceManager.GetObject("EditModpackBadIdentifier", resourceCulture)); }
        }
        internal static string EditModpackBadName {
            get { return (string)(ResourceManager.GetObject("EditModpackBadName", resourceCulture)); }
        }
        internal static string EditModpackBadVersion {
            get { return (string)(ResourceManager.GetObject("EditModpackBadVersion", resourceCulture)); }
        }
        internal static string EditModpackBadKspVersions {
            get { return (string)(ResourceManager.GetObject("EditModpackBadKspVersions", resourceCulture)); }
        }
        internal static string EditModpackTooltipIdentifier {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipIdentifier", resourceCulture)); }
        }
        internal static string EditModpackTooltipName {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipName", resourceCulture)); }
        }
        internal static string EditModpackTooltipAbstract {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipAbstract", resourceCulture)); }
        }
        internal static string EditModpackTooltipVersion {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipVersion", resourceCulture)); }
        }
        internal static string EditModpackTooltipKspVersionMin {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipKspVersionMin", resourceCulture)); }
        }
        internal static string EditModpackTooltipKspVersionMax {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipKspVersionMax", resourceCulture)); }
        }
        internal static string EditModpackTooltipLicense {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipLicense", resourceCulture)); }
        }
        internal static string EditModpackTooltipIncludeVersions {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipIncludeVersions", resourceCulture)); }
        }
        internal static string EditModpackTooltipDepends {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipDepends", resourceCulture)); }
        }
        internal static string EditModpackTooltipRecommends {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipRecommends", resourceCulture)); }
        }
        internal static string EditModpackTooltipSuggests {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipSuggests", resourceCulture)); }
        }
        internal static string EditModpackTooltipIgnore {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipIgnore", resourceCulture)); }
        }
        internal static string EditModpackTooltipCancel {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipCancel", resourceCulture)); }
        }
        internal static string EditModpackTooltipExport {
            get { return (string)(ResourceManager.GetObject("EditModpackTooltipExport", resourceCulture)); }
        }
   }
}
