name: Test CKAN + NetKAN

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
  workflow_call:

jobs:
  build-debug:
    uses: ./.github/workflows/build.yml
  test-build:
    needs: build-debug
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install runtime dependencies
        run: sudo apt-get install -y xvfb
      - name: Download out artifact
        uses: actions/download-artifact@v4
        with:
          name: Debug-out-unsigned
          path: _build/out/
      - name: Restore permissions discarded by zip/unzip of artifact
        run: |
          chmod a+x _build/out/Build/*/bin/net8.0/Build _build/out/Build/*/obj/*/net8.0/apphost
      - name: Download repack artifact
        uses: actions/download-artifact@v4
        with:
          name: Debug-repack-unsigned
          path: _build/repack/
      - name: Run tests
        run: xvfb-run ./build.sh test+only --configuration=Debug --where="Category!=FlakyNetwork"
      - name: Report Coveralls
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  # notify:
  #   needs:
  #     - build-debug
  #     - test-build
  #   if: failure()
  #   uses: ./.github/workflows/notify.yml
  #   with:
  #     name: ${{ github.workflow }}
  #     success: ${{ !contains(needs.*.result, 'failure') }}
  #   secrets: inherit
